services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - app_network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quant_trade
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    networks:
      - app_network
    depends_on:
      - app

volumes:
  postgres_data:
networks:
  app_network:
